version: '3.4'

services:
  backend:
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=1433
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"
  client:
    ports:
      - "5001:3000"
 